Add calibration status
tier4/AutowareArchitectureProposal_msgs pull request #19
Opened 2022-03-11 09:02 UTC by TakumiKozaka-T4

## Related Links

## Description

Add CalibrationStatus.msg and CalibrationDataRequest.srv. This is for cooperation with FMS.

## Remarks

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Code is properly formatted
- [x] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] Code is properly formatted
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets
- [ ] Write [release notes][release-notes]

## CI Checks

- **Build and test for PR**: Required to pass before the merge.
- **Check spelling**: NOT required to pass before the merge. It is up to the reviewer(s). See [here][spell-check-dict] if you want to add some words to the spell check dictionary.

[release-notes]: https://tier4.atlassian.net/wiki/spaces/AIP/pages/563774416
[spell-check-dict]: https://github.com/tier4/autoware-spell-check-dict#how-to-contribute

2022-03-14 06:36 UTC, isamu-takagi requested changes, later dismissed

2022-03-14 06:36 UTC, isamu-takagi commented on tier4_external_api_msgs/srv/CalibrationDataRequest.srv
> +bool data_request
What is this data used for? If it is not needed, remove this line like the [Trigger.srv](https://github.com/ros2/common_interfaces/blob/master/std_srvs/srv/Trigger.srv).

2022-03-14 06:36 UTC, isamu-takagi commented on tier4_external_api_msgs/srv/CalibrationDataRequest.srv
> +float32[] brake_map
The format of accel_map and brake_map is a CSV, so we need a 2D array or column size.
Moreover, the first column may be the string "default".

2022-03-22 05:11 UTC, isamu-takagi commented on tier4_external_api_msgs/msg/CalibrationStatus.msg
> +uint8 ACCELBRAKEMAP=1
```suggestion
uint8 ACCEL_BRAKE_MAP=1
```

2022-03-22 05:13 UTC, isamu-takagi reviewed
Could you add a space for comments?

2022-03-22 05:13 UTC, isamu-takagi commented on tier4_external_api_msgs/msg/CalibrationStatus.msg
> +#calibration target
```suggestion
# calibration target 
```

2022-03-22 05:13 UTC, isamu-takagi commented on tier4_external_api_msgs/msg/CalibrationStatus.msg
> +#status constants
```suggestion
# status constants
```

2022-03-22 05:13 UTC, isamu-takagi commented on tier4_external_api_msgs/msg/CalibrationStatus.msg
> +#fields
```suggestion
# fields
```

2022-03-22 05:30 UTC, isamu-takagi commented
@TakumiKozaka-T4 
The name `CalibrationStatusStamped` seems a pair of time stamp and single `CalibrationStatus`,
so I think the following is preferred:
* `CalibrationStatus` + `CalibrationStatusArray`
* `CalibrationStatus` + `CalibrationStatuses`
* `CalibrationModuleStatus` + `CalibrationStatus`

2022-06-15 00:55 UTC, yabuta approved these changes
LGTM

2022-06-15 00:57 UTC, merged